[default]
env = "testing"
name = "Python Projeto Base"
version = "0.1.0"
debug = false

[development]
ambiente = "desenvolvimento"
debug = true

[production]
ambiente = "producao"

[testing]
ambiente = "testes"
